// GENERATED by /api/dev/keep-take — do not hand-edit.
// Every roll kept in the dev curation panel ships, and deleting one there drops
// it from this list: the kept rolls ARE the shipped set, there is no bake step.
import type { RollInTake } from "../introDriver";
import t1784849832708 from "./take-1784849832708.json";
import t1784850377388 from "./take-1784850377388.json";
import t1784852967997 from "./take-1784852967997.json";
import t1784853061777 from "./take-1784853061777.json";
import t1784853101331 from "./take-1784853101331.json";
import t1784853287933 from "./take-1784853287933.json";
import t1784853338997 from "./take-1784853338997.json";

export const TAKE_NAMES = [
  "take-1784849832708.json",
  "take-1784850377388.json",
  "take-1784852967997.json",
  "take-1784853061777.json",
  "take-1784853101331.json",
  "take-1784853287933.json",
  "take-1784853338997.json",
];

export const TAKES: RollInTake[] = [
  t1784849832708.take,
  t1784850377388.take,
  t1784852967997.take,
  t1784853061777.take,
  t1784853101331.take,
  t1784853287933.take,
  t1784853338997.take,
];
